### ISSUE TITLE
Compiles, runs, exits

### ISSUE THREAD

**Issue by Glenn1963** [alejandromarcu/DominoTrack#1]
I hate to annoy, so please feel free to ignore this, but I'm looking for some help just getting this to run after I compile it.

I can get it to compile and run, it appears onscreen then immediately exits. At the same time the world goes to the white environment in the headset and returns home.

Do I need more in my environment to build, or are there settings I should be using? Then there's the 'Unity Services' warning.

Or is it likely that it's bad that I ended up with newer versions of some of the modules?

Either way I appreciate you putting your creation out here for public consumption.

Thanks...

-G

**Comment by alejandromarcu** [comment]
Happy to see that someone is interested in this!
What version of Unity are you using?
Are you using Oculus Rift? I haven't tested it in any other platforms, I doubt it would work
Have you tried the app directly from the oculus store?
Can you paste the warnings that you get?
I tried to include everything that is needed in the repo, but I may have missed something

**Comment by Glenn1963** [comment]
Thanks for getting back to me :)
Unity 2017.4.0f1 (64-bit) personal
Rift, and the app runs perfectly from the store, which led me to here.
When I first loaded the project there were several messages about newer versions of various libraries, which I chose to let it upgrade. There were also some warnings for deprecated code, which I changed and hope will be ok. But I finally figured out that I'm getting an entitlement error. (Attached).
![capture2](https://user-images.githubusercontent.com/17497231/37988208-2ea6e682-31b5-11e8-92cb-dbb384e6b25a.JPG)

Do I need my own appid, or some other way to test this?

This is the other message I get when building:

![capture](https://user-images.githubusercontent.com/17497231/37988235-3e3620cc-31b5-11e8-8142-8b4553da320f.JPG)

Thanks again!

-G

**Comment by alejandromarcu** [comment]
I'd think that the entiltment check would work since you installed it already from the store.
You can try just disabling the entiltment check, you can just delete EntitlementCheck.cs or change it to do nothing.
The unity services is not an issue.  I don't think the other warnings are an issue either, so I'd start just with the entiltment check

**Comment by Glenn1963** [comment]
Disable the entitlement check, sure, when you say it out loud it seems obvious :) I assumed it was necessary. 

But that worked, so cool. Compiled and ran no problem, just like the store version. 
I wasn't replacing the store copy, that may have made a difference if I had run it from Home. 

I really appreciate this. Hoping to learn a little about coding in this environment, if I come up with anything useful I'll let you know!

**Comment by alejandromarcu** [comment]
Happy to hear!
The entitlement check is required to publish in the oculus store, so that people can't just redistribute the application.  If you don't have the entitlement check, oculus would reject it.  But definitely you can run it locally without that, in fact I didn't have it until the end.
It's my first app for Oculus and in C#, so I may not be doing things the best way.
I tried to do small well contained commits, and that may help you better understand the code
